services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
      POSTGRES_DB: "Auctions"
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpw"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mongo

volumes:
  postgresdata:
  mongodata:

