import React from 'react'
import './globals.css'
import Navbar from '@/app/nav/Navbar'
import {getCurrentUser} from "@/app/actions/authActions";
import ToasterProvider from "@/app/providers/ToasterProvider";
import SignalRProvider from "@/app/providers/SignalRProvider";


export const metadata = {
  title: 'AuctionNext',
  description: 'Generated by create next app',
}

export default async function RootLayout({children,}: { children: React.ReactNode }) {
  const user = await getCurrentUser();
  return (
      <html lang="en">
      <body>
      <ToasterProvider/>
      <Navbar/>
      <main className='container mx-auto px-5 pt-10'>
        <SignalRProvider user={user}>
          {children}
        </SignalRProvider>
      </main>
      </body>
      </html>
  )
}
