name: apply-k8s

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save auctionnext
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/prod-k8s
